config/routes.rb
Rails.application.routes.draw do
  resources :instructors do
    collection do
      get 'search'
    end
  end
  resources :private_notes do
    collection do
      get 'search'
    end
  end
  get 'search/tags_for', controller: :search, action: :tags_for
  post 'search/targeted', controller: :search, action: :targeted
  get :search, controller: :search, action: :input
  post :search, controller: :search, action: :advanced
  get 'search/a', controller: :search, action: :autocomplete

  get 'stats/site', controller: :stats, action: :site

  get 'links/without_instructors', controller: :links, action: :index_without_instructors
  get 'links/tag_filter', controller: :links, action: :index_based_on_tags
  
  get 'validate/email', to: 'validations#email'
  get 'validate/instructor', to: 'validations#instructor'
  get 'validate/url', to: 'validations#url'
  
  resources :comments
  get 'notebook', controller: :private_notes, action: :notebook
  resources :tags
  resources :reviews
  get 'gyms/admin_index', controller: :gyms, action: :admin_index
  resources :gyms do
    put :publish
    put :unpublish
    put :flag
    put :reject
    put :verify
    collection do
      get 'search'
    end
  end
  resources :links do
    post :ratings, to: 'ratings#rate'
    patch :ratings, to: 'ratings#rate'
    resources :comments, only: [:create, :index, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    get 'favorites'
    get 'reviews'
  end

  authenticated :user do
    root 'users#dashboard'
  end
  root to: 'visitors#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :force_json, only: [:autocomplete, :tags_for]

  def autocomplete
    @tags = Tag.ransack(full_tag_cont: params[:q]).result(distinct: true).limit(5)
    @links = Link.ransack(title_cont: params[:q]).result(distinct: true).limit(5)
    @instructors = Instructor.ransack(all_names_cont: params[:q]).result(distinct: true).limit(5)
  end

  def tags_for
    @tags = case params[:iwant]
    when 'escape', 'defend', 'counter', 'learn', 'flow', 'drill'
      Tag.position_submission
    when 'submit', 'pass'
      Tag.positions
    else
      Tag.all
    end
  end

  def targeted
    pajama_status = get_pajama_status(params[:gi], params[:nogi])
    tags_to_search = params[:tag_ids].present? ?
      [params[:tag_ids] + pajama_status].flatten :
      pajama_status

    want_tags = case params[:iwant]
    when 'counter', 'escape', 'defend'
      Tag.where(full_name: ['move::counter', 'move::escape', 'move::defense']).ids
    when 'submit'
      Tag.where(full_name: ['move::submission']).ids
    when 'drill', 'flow'
      Tag.where(full_name: ['move::drill', 'move::flow', 'move::warmup']).ids
    when 'learn'
      Tag.where(full_name: ['move::drill', 'move::theory']).ids
    when 'pass'
      Tag.where(full_name: ['move::pass', 'move::sweep']).ids
    else
      # we should never get here, but let's have tags just in case
      Tag.all
    end

    if params[:tag_ids].present?
      @pagy, @links = pagy(Link.joins(:tags).where("tags.id" => want_tags).by_tags(tags_to_search).order(created_at: :desc), items: 25)
    else
      if tags_to_search.empty?
        @pagy, @links = pagy(Link.joins(:tags).where("tags.id" => want_tags).distinct('links.id').order(created_at: :desc), items: 25)
      else
        # FIXME this query doesn't work properly. It needs to actually do an OR of tuples where the tuple is like (nogi, pass) OR (nogi, sweep) I think.
        @pagy, @links = pagy(Link.joins(:tags).where("tags.id" => want_tags).where("tags.id" => tags_to_search).distinct('links.id').order(created_at: :desc), items: 25)
      end
    end
  
    respond_to do |format|
      format.js
    end
  end

  def input
    render 'new' if params[:q].blank? or params[:q].length < 2
    @tags = Tag.ransack(full_tag_cont: params[:q]).result(distinct: true)
    @links = Link.ransack(title_cont: params[:q]).result(distinct: true).order(created_at: :desc)
    @instructors = Instructor.ransack(all_names_cont: params[:q]).result(distinct: true)
    @private_notes = if current_user
                       PrivateNote.where(user_id: current_user.id).ransack(
        body_cont: params[:q],
        title_cont: params[:q],
        m: 'or'
    ).result(distinct: true)
                     else
                       []
                     end
    @total_results = @links.size + @tags.size + @instructors.size + @private_notes.size
  end

  def advanced
    @links = params[:tag_ids] ?
      Link.by_tags(params[:tag_ids]).ransack(title_cont: params[:q]).result(distinct: true).order(created_at: :desc) :
      Link.ransack(title_cont: params[:q]).result(distinct: true).order(created_at: :desc)
    
    @tags = []
    @instructors = []
    @total_results = @links.count
    render 'input'
  end

  private

    def force_json
      request.format = :json
    end

    def get_pajama_status(gi, nogi)
      if gi and !nogi
        return [Tag.where(full_name: 'uniform::gi').limit(1).ids]
      elsif !gi and nogi
        return [Tag.where(full_name: 'uniform::nogi').limit(1).ids]
      else
        return []
      end
    end
end

app/helpers/search_helper.rb
module SearchHelper
  def display_search_parameters(result_count, params)
    # Add the below code to this
 ####     <% if @total_results > 0 %>
 ####       <h2 class="lead"><strong class="text-danger"><%= @total_results %></strong> results were found for the search for <%= display_search_parameters(params) %></h2>
 ####     <% else %>
 ####       <h2 class="lead">No results found for <strong class="text-danger"><%= params[:q] %></strong></h2>
 ####     <% end %>

    rv = '<h2 class="lead">' + pluralize(result_count, "result") + '</h2>'

    if params[:q]
      rv = rv + "<h2 class='lead'>Term: <strong class='text-danger'>#{params[:q]}</strong></h2>"
    end

    if params[:tag_ids].present? and params[:tag_ids].length > 0
      rv = rv + "<h2 class='lead'>Tags: "
      Tag.where(id: params[:tag_ids]).each do |tag|
        rv = rv + link_to(tag.full_name, tag, class: 'tag')
      end
      rv = rv + "</h2>"
    end
    rv.html_safe
  end
end

app/views/search/_link_search_result.html.erb
		<article class="search-result row">
			<div class="col-xs-12 col-sm-12 col-md-3">
        <%= link_to image_tag(link.thumbnail_image_location(250,140), alt: link.title, height: '140px', width: '250px'), link %>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-2">
				<ul class="meta-search">
          <li><i class="pt-1 pr-3 mr-2 glyphicon-calendar"></i> <span><%= link.created_at.strftime("%Y-%b-%d") %></span></li>
          <li><i class="pt-1 pr-3 mr-2 glyphicon-user"></i> <span><%= link_to link.user.name, link.user %></span></li>
          <% link.instructors.take(2).each do |i| %>
            <li><span><%= link_to i.nickname_or_name, i, class: 'btn btn-sm btn-light' %></span></li>
          <% end %>
				</ul>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-7 excerpet">
        <h3><%= link_to link.title, link %></h3>
        <% if link.description_exists? %>
          <p><%= link.show_description %></p>
        <% end %>
        <ul>
          <% link.tags.each do |tag| %>
            <%= link_to tag.full_name, tag, class: 'tag' %>
          <% end %>
        </ul>
			</div>
		</article>

app/views/search/_private_note_search_result.html.erb
<div class="card border-0">
            <div class="notebook-paper mb-2">
              <div class="notebook-content">
                <div class="notebook-header">
                  <h3 class="notebook-title"><%= truncate(note.title, length: 20) %></h3>
                  <h6 class="notebook-title"><%= link_to truncate(note.link.title, length: 28), link_path(note.link) %></h6>
                </div>
                <p><%= truncate(note.body, length: 100) %></p>
              </div>
            </div>
</div>

app/views/search/_search_bar.html.erb
<hr />

<%= form_tag(search_targeted_path, method: :post, class: 'form-inline', remote: true) do %>
  <div class="row w-100">
    <div class="col-sm-1 col-md-1 col-lg-2 col-xl-2">
      <span class="text-right align-baseline">I want to</span>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">
      <%= select_tag "iwant", options_for_select(Tag::TARGETED_SEARCH_OPTIONS.sort, "submit") %>
    </div>

    <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1">
      <strong><span id="part_of_speech" class="text-center align-baseline">from</span></strong>
    </div>

    <div class="col-sm-2 col-md-3 col-lg-4 col-xl-4">
      <%= select_tag :tag_ids,
        options_for_select(Tag.positions.map {|t|  [t.search_name, t.id]}.sort),
        { multiple: true, id: 'iwant_search_tag_ids' }
      %>
    </div>

    <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1">
      <strong><span class="text-center align-baseline">in</strong>
    </div>

    <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1 justify-content-start">
      <div class="form-check justify-content-start">
        <%= check_box_tag "nogi", true, true, class: 'form-check-input' %>
        <%= label_tag "nogi", "nogi", class: 'form-check-label' %>
      </div>
      <div class="form-check justify-content-start">
        <%= check_box_tag "gi", true, true, class: 'form-check-input' %>
        <%= label_tag "gi", "gi", class: 'form-check-label' %>
      </div>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1">
      <%= submit_tag 'Search', id: 'specialty-search', class: 'form-control btn btn-light' %>
    </div>
  </div>
<% end %>

<hr />

<div class="row">
  <div class="col">
    <div id="search-results-div">
    </div>
  </div>
</div>

app/views/search/_targeted_results.html.erb
<div class="text-center pr-2 pl-2">
  <% if @links.empty? %>
    <h5 class="mb-2">We Ain't Found Shit!</h5>
    <%= image_tag 'we-aint-found-shit.jpg', class: 'img-fluid' %>
  <% else %>
    <h5><%= pluralize(@links.count, "video") %></h5>
  <% end %>
</div>

app/views/search/input.html.erb
<div class="col">
  <h1 class="mt-4">Search Results</h1>
  <div class="col">
    <%= display_search_parameters(@total_results, params) %>
  </div>

  <hr />

  <div class="row">
    <% if @instructors.size > 0 %>
	    <div class="col-xs-12 col-sm-12 col-md-2 border-right">
        <h3><%= pluralize(@instructors.count, "instructor").capitalize %></h3>
        <% @instructors.each do |instructor| %>
          <%= link_to instructor.nickname_or_name, instructor, class: 'btn btn-light' %>
        <% end %>
      </div>
    <% end %>

    <% if @tags.size > 0 %>
			  <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><%= pluralize(@tags.count, "tag").capitalize %></h3>
          <% @tags.each do |tag| %>
            <%= link_to tag.full_name, tag, class: 'tag' %>
          <% end %>
        </div>
    <% end %>

  </div>

  <% if @links.size > 0 %>
    <div class="row">
      <div class="col">
        <h3><%= pluralize(@links.count, "video").capitalize %></h3>
        <% @links.each do |link| %>
          <%= render partial: 'search/link_search_result', locals: { link: link } %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @private_notes.size > 0 %>
    <hr />
    <div class="row mt-2 mb-1">
      <div class="col">
        <h3 class="mb-2">
          <%= pluralize(@private_notes.count, "notebook entry").capitalize %>
          <small class="text-muted">(only you can see your notes)</small>
        </h3>
        <div class="container">
          <div class="card-columns">
            <% @private_notes.each do |note| %>
              <%= render partial: 'search/private_note_search_result', locals: { note: note } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>


</div>

app/views/search/new.html.erb
<div class="col">
  <h1 class="mt-4">Search</h1>

  <div class="row">
    <div class="col-lg-8">
      <%= form_tag(search_path method: :post) do %>
        <div class="form-row">
          <div class="my-1 col-2 text-left">
            <%= label_tag "Videos", nil, class: "col-form-label-lg pr-2" %>
          </div>
          <div class="my-1 col-4">
            <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: "Search string" %>
          </div>
        </div>
        <div class="form-row">
          <div class="my-1 col-2 text-left">
            <%= label_tag "tagged with", nil, class: "col-form-label-lg pr-2" %>
          </div>
          <div class="my-1 col-4">
            <%= select_tag :tag_ids,
              options_for_select(Tag.all.map {|t|  [t.full_name, t.id]}.sort),
              { include_blank: true, multiple: true, id: 'search_tag_ids' }
            %>
          </div>
        </div>
        <div class="form-row">
          <div class="my-1 col-6">
            <%= submit_tag 'Search', class: 'btn btn-light' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="card my-4">
        <h5 class="card-header">Search Help</h5>
        <div class="card-body">
          <ul class="list-group">
            <li class="list-group-item">
              Tags are optional. When they are included, they are AND'd. "art::bjj AND uniform::nogi"
            </li>
            <li class="list-group-item">
              Search box with no tags will just search all videos, instructors, and tags.
            </li>
            <li class="list-group-item">
              Search box and tags will ONLY search videos tagged with the AND'd tag list for the text in the search box.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/targeted.js.erb
$(function(){
  <% if @links.size > 0 %>
    $('#main-cards').html(`<%= render partial: 'links/cards', locals: { links: @links } %>`).show();
    $('#pagy-container').show();
    $('#pagy-div').html('<%== pagy_nav_bootstrap(@pagy) %>');
  <% else %>
    $('#main-cards').hide();
    $('#pagy-container').hide();
    $('span#results-text').addClass("text-danger").text("We ain't found sh*t!").show();
  <% end %>

  // this get rendered no matter what
    $('div#search-results-div').html(`<%= render partial: 'search/targeted_results', locals: { links: @links } %>`);
});