config/routes.rb
Rails.application.routes.draw do
  resources :instructors do
    collection do
      get 'search'
    end
  end
  resources :private_notes do
    collection do
      get 'search'
    end
  end
  get 'search/tags_for', controller: :search, action: :tags_for
  post 'search/targeted', controller: :search, action: :targeted
  get :search, controller: :search, action: :input
  post :search, controller: :search, action: :advanced
  get 'search/a', controller: :search, action: :autocomplete

  get 'stats/site', controller: :stats, action: :site

  get 'links/without_instructors', controller: :links, action: :index_without_instructors
  get 'links/tag_filter', controller: :links, action: :index_based_on_tags
  
  get 'validate/email', to: 'validations#email'
  get 'validate/instructor', to: 'validations#instructor'
  get 'validate/url', to: 'validations#url'
  
  resources :comments
  get 'notebook', controller: :private_notes, action: :notebook
  resources :tags
  resources :reviews
  get 'gyms/admin_index', controller: :gyms, action: :admin_index
  resources :gyms do
    put :publish
    put :unpublish
    put :flag
    put :reject
    put :verify
    collection do
      get 'search'
    end
  end
  resources :links do
    post :ratings, to: 'ratings#rate'
    patch :ratings, to: 'ratings#rate'
    resources :comments, only: [:create, :index, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    get 'favorites'
    get 'reviews'
  end

  authenticated :user do
    root 'users#dashboard'
  end
  root to: 'visitors#index'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  include Impressionist::IsImpressionable
  is_impressionable

  has_and_belongs_to_many :links

  validates :name, presence: true, length: { minimum: 3 }

  ransack_alias :all_names, :nickname_or_name

  def has_videos?
    self.links.count > 0
  end

  def video_count
    self.links.count
  end

  def form_display_name
    rv = "#{self.name}"
    if self.instagram.present?
      rv = rv + " (#{self.instagram})"
    elsif self.nickname.present?
      rv = rv + " (#{self.nickname})"
    end
    return rv
  end

  def display_name
    rv = "#{self.name}"
    rv = rv + " (#{self.nickname})" if self.nickname.present?
    return rv
  end

  def nickname_or_name
    self.nickname.present? ? self.nickname : self.name
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized
  impressionist :actions => [:show]
  respond_to :js, :html

  # GET /instructors
  # GET /instructors.json
  def index
    @pagy, @instructors = pagy(Instructor.order(name: :asc), items: 25)
    authorize @instructors
  end

  def search
    authorize Instructor
    @pagy, @instructor_search = pagy(
      Instructor.ransack(
        name_cont: params[:instructor_search],
        nickname_cont: params[:instructor_search],
        description_cont: params[:instructor_search],
        instagram_cont: params[:instructor_search],
        youtube_cont: params[:instructor_search],
        twitter_cont: params[:instructor_search],
        facebook_cont: params[:instructor_search],m:'or'
        ).result(distinct: true), 
      items:25, 
      link_extra: 'data-remote="true"'
    )
    respond_to do |format|
      format.js
    end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    authorize @instructor
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
    authorize @instructor
  end

  # GET /instructors/1/edit
  def edit
    authorize @instructor
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)
    authorize @instructor

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to instructors_path, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    authorize @instructor
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    authorize @instructor
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :nickname, :description, :instagram, :youtube, :twitter, :facebook)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
    def social_media_helper_short(instructor)
        if instructor.instagram.present? && !instructor.instagram[1..-1].empty?
            instagram = "<a target='_blank' href='" + "https://instagram.com/" + instructor.instagram[1..-1] + "'>IG</a>" 
        end

        if instructor.twitter.present? && !instructor.twitter[1..-1].empty?
            twitter = "<a target='_blank' href='" + "https://twitter.com/" + instructor.twitter[1..-1] + "'>Tw</a>"
        end

        facebook = "<a target='_blank' href='" + instructor.facebook + "'>FB</a>" if instructor.facebook.present?
        youtube = "<a target='_blank' href='" + "https://youtube.com/user/" + instructor.youtube + "'>YT</a>" if instructor.youtube.present?
        website = "<a target='_blank' href='" + instructor.website + "'>W</a>" if instructor.website.present?

        final_string = [instagram, twitter, facebook, youtube, website].reject{ |link| link == nil }
        return final_string.join(' &nbsp;').html_safe
    end

    def social_media_helper(instructor)
        if instructor.instagram.present? && !instructor.instagram[1..-1].empty?
            instagram = "<a href='" + "https://instagram.com/" + instructor.instagram[1..-1] + "'>" + "https://instagram.com/" + instructor.instagram[1..-1] + "</a></br>" 
        end
        if instructor.twitter.present? && !instructor.twitter[1..-1].empty?
            twitter = "<a href='" + "https://twitter.com/" + instructor.twitter[1..-1] + "'>" + "https://twitter.com/" + instructor.twitter[1..-1] + "</a></br>"
        end

        facebook = "<a href='" + instructor.facebook + "'>" + instructor.facebook + "</a></br>" if instructor.facebook.present?
        youtube = "<a href='" + "https://youtube.com/user/" + instructor.youtube + "'>" + "https://youtube.com/user/" + instructor.youtube + "</a>" if instructor.youtube.present?

        website = "<a href='" + instructor.website + "'>" + instructor.website + "</a></br>" if !instructor.website.present?

        final_string = [instagram, twitter, facebook, youtube, website].reject{ |link| link == nil }
        return final_string.join('').html_safe
    end
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-row">
    <%= form.label :name, class: 'col-form-label-lg' %>
    <%= form.text_field :name, :autofocus => true, class: 'form-control', required: true %>
    <small id="instructor_name_help" class="form-text text-muted w-100">Unique name for every instructor.</small>
    <div id="instructor_name_validation" class="w-100">
      Instructor name already taken
    </div>
  </div>

  <div class="form-group form-row">
    <%= form.label :nickname, class: 'col-form-label-lg' %>
    <%= form.text_field :nickname, class: 'form-control' %>
  </div>

  <div class="form-group form-row">
    <%= form.label :instagram, class: 'col-form-label-lg' %>
    <%= form.text_field :instagram, class: 'form-control' %>
    <small id="instructor_instagram_help" class="form-text text-muted w-100">Just the Instagram handle (eg. @elubow).</small>
  </div>

  <div class="form-group form-row">
    <%= form.label :youtube, class: 'col-form-label-lg' %>
    <%= form.text_field :youtube, class: 'form-control' %>
    <small id="instructor_youtube_help" class="form-text text-muted w-100">Just the Youtube channel (eg. ericlubow).</small>
  </div>

  <div class="form-group form-row">
    <%= form.label :facebook, class: 'col-form-label-lg' %>
    <%= form.text_field :facebook, class: 'form-control' %>
    <small id="instructor_facebook_help" class="form-text text-muted w-100">The entire facebook link.</small>
  </div>

  <div class="form-group form-row">
    <%= form.label :twitter, class: 'col-form-label-lg' %>
    <%= form.text_field :twitter, class: 'form-control' %>
    <small id="instructor_twitter_help" class="form-text text-muted w-100">Just the Twitter handle (eg. @elubow).</small>
  </div>

  <div class="form-group form-row">
    <%= form.label :description, class: 'col-form-label-lg' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group mt-4">
    <%= form.submit 'Save Instructor', class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/instructors/_list.html.erb
<table class="table table-hover">
    <thead>
      <tr>
        <th>Videos</th>
        <th>Name</th>
        <th>Nickname</th>
        <th>Social</th>
        <th>Description</th>
        <% if current_user %>
          <th colspan="3">Actions</th>
        <% end %>
      </tr>
    </thead>
  
    <tbody>
      <% instructors.each do |instructor| %>
        <tr>
          <td><%= link_to instructor.links.count, instructor %></td>
          <td><%= link_to instructor.name, instructor %></td>
          <td><%= instructor.nickname %></td>
          <td><%= social_media_helper_short(instructor) %></td>
          <td><%= instructor.description %></td>
          <% if current_user %>
            <% if current_user.moderator? or current_user.admin? %>
              <td><%= link_to 'Edit', edit_instructor_path(instructor), class: 'btn btn-primary' %></td>
            <% end %>
            <% if current_user.admin? %>
              <td><%= link_to 'Delete', instructor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/instructors/edit.html.erb
<div class="col">
  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h1 class="mt-4">Edit Instructor</h1>
        </div>
        <div class="card-body">

          <%= render 'form', instructor: @instructor %>
        </div>
      </div>
    </div>

    <div class="col-3">
    </div>
  </div>
</div>

</div>

app/views/instructors/index.html.erb
<div class="col">

  <h1 class="mt-4"><%= title "Instructors" %></h1>
  <% if current_user %>
    <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-secondary float-right mb-2' %>
  <% end %>

  <%= form_with url: search_instructors_path, method: :get do |f|%>
    <div class="form-group row">
      <label class="col-form-label col-1 text-right"><h6>Search</h6></label>
      <div class="col-3">
        <%= f.text_field :instructor_search, class: 'form-control' %>
        <div style="display:none;"><%= f.submit id: 'submit-search' %></div>
      </div>
      <div class="col-9">
      </div>
    </div>
  <% end %>
  
  <div id="instructor-display"><%= render partial: 'instructors/list', locals: { instructors: @instructors } %></div>

  <div class="row">
    <div class="col">
      <div id="pagy-div" class="d-flex justify-content-center">
        <%== pagy_nav_bootstrap(@pagy) %>
      </div>
    </div>
  </div>
 
<% if current_user %>
  <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-secondary' %>
<% end %>

app/views/instructors/new.html.erb
<div class="col">
  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h1 class="mt-4">New Instructor</h1>
        </div>
        <div class="card-body">

          <%= render 'form', instructor: @instructor %>
        </div>
      </div>
    </div>

    <div class="col-3">
    </div>
  </div>
</div>

</div>

app/views/instructors/search.js.erb
$(function(){
    $('#instructor-display').html(`<%= render partial: 'instructors/list', locals: { instructors: @instructor_search } %>`);
    $('#pagy-div').html('<%== pagy_nav_bootstrap(@pagy) %>');
});

app/views/instructors/search_for.js.erb
$(function(){
    $('#instructor-display').html(`<%= render partial: 'instructors/list', locals: { instructors: @instructor_search } %>`);
    $('#pagy-div').html('<%== pagy_nav_bootstrap(@pagy) %>');
});

app/views/instructors/show.html.erb
<% title "Videos taught by #{@instructor.display_name}" %>
<% description @instructor.description %>
<% set_meta_tags canonical: request.url %>
<% set_meta_tags keywords: [@instructor.display_name] %>
<% set_meta_tags og: {
  title: "Videos taught by #{@instructor.display_name}",
  description: truncate(@instructor.description, length: 254, separator: /\w+/),
} %>


<div class="col">
  <h1 class="mt-4">
    <%= @instructor.display_name %>
  </h1>

  <h4 class="ml-4 mb-3">
    <%= social_media_helper_short(@instructor) %>
  </h4>

  <% if @instructor.has_videos? %>
    <%= image_tag(@instructor.links.first.thumbnail_image_location(), alt: @instructor.display_name, class: 'link_image') %>
  <% end %>
  
  <% if @instructor.description? %>
  <p class="mt-2">
    <%= @instructor.description %>
  </p>
  <% end %>
  
  <% if current_user %>
    <div class="row">
      <div class="col-9">
      </div>
      <div class="col-3 text-right">
        <% if current_user.moderator? or current_user.admin? %>
          <%= link_to 'Edit', edit_instructor_path(@instructor), class: 'btn btn-primary' %>
        <% end %>
        <% if current_user.admin? %>
          | <%= link_to 'Delete', @instructor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @instructor.has_videos? %>
    <h4 class="mt-2"><%= pluralize(@instructor.video_count, "Videos").titleize %></h4>
    <%= render partial: 'links/list', locals: {links: @instructor.links} %>
  <% else %>
    <p>
    If you can believe it, <strong><%= @instructor.name %></strong> hasn't put out a single video.
    </p>
    <p>
      <% if current_user %>
        <%= link_to "Add Video", new_link_path, class: 'btn btn-primary' %>
      <% end %>
    </p>
  <% end %>
</div>