config/routes.rb
Rails.application.routes.draw do
  resources :instructors do
    collection do
      get 'search'
    end
  end
  resources :private_notes do
    collection do
      get 'search'
    end
  end
  get 'search/tags_for', controller: :search, action: :tags_for
  post 'search/targeted', controller: :search, action: :targeted
  get :search, controller: :search, action: :input
  post :search, controller: :search, action: :advanced
  get 'search/a', controller: :search, action: :autocomplete

  get 'stats/site', controller: :stats, action: :site

  get 'links/without_instructors', controller: :links, action: :index_without_instructors
  get 'links/tag_filter', controller: :links, action: :index_based_on_tags
  
  get 'validate/email', to: 'validations#email'
  get 'validate/instructor', to: 'validations#instructor'
  get 'validate/url', to: 'validations#url'
  
  resources :comments
  get 'notebook', controller: :private_notes, action: :notebook
  resources :tags
  resources :reviews
  get 'gyms/admin_index', controller: :gyms, action: :admin_index
  resources :gyms do
    put :publish
    put :unpublish
    put :flag
    put :reject
    put :verify
    collection do
      get 'search'
    end
  end
  resources :links do
    post :ratings, to: 'ratings#rate'
    patch :ratings, to: 'ratings#rate'
    resources :comments, only: [:create, :index, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    get 'favorites'
    get 'reviews'
  end

  authenticated :user do
    root 'users#dashboard'
  end
  root to: 'visitors#index'
end

app/models/private_note.rb
class PrivateNote < ApplicationRecord
  belongs_to :user
  belongs_to :link

  validates :body, presence: true, allow_blank: false
end

app/controllers/private_notes_controller.rb
class PrivateNotesController < ApplicationController
  before_action :get_link, only: [:create]
  before_action :set_private_note, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /notebook
  # GET /notebook.json
  def notebook
    @pagy, @private_notes = pagy(PrivateNote.where(user: current_user).order(created_at: :desc), items: 5)
    authorize @private_notes
  end

  # GET /private_notes
  # GET /private_notes.json
  def index
    @pagy, @private_notes = pagy(PrivateNote.order(created_at: :desc), items: 25)
    authorize @private_notes
  end

  def search
    authorize PrivateNote
    @pagy, @private_notes_search = pagy(
      PrivateNote.where(user_id: current_user.id).ransack(
        body_cont: params[:private_note_search],
        title_cont: params[:private_note_search],
        m: 'or'
      ).result(distinct: true),
      items: 10,
      link_extra: 'data-remote="true"'
    )
    respond_to do |format|
      format.js
    end
  end

  # GET /private_notes/1
  # GET /private_notes/1.json
  def show
    @private_note = PrivateNote.find(params[:id])
    authorize @private_note
  end

  # GET /private_notes/new
  def new
    @private_note = PrivateNote.new
    authorize @private_note
  end

  # GET /private_notes/1/edit
  def edit
    authorize @private_note
  end

  # POST /private_notes
  # POST /private_notes.json
  def create
    @private_note = PrivateNote.new(private_note_params)
    authorize @private_note
    @private_note.user_id = current_user.id

    respond_to do |format|
      if @private_note.save
        format.html { redirect_to @link, notice: 'Note added to your notebook.' }
        format.json { render :show, status: :created, location: @private_note }
      else
        format.html { render :new }
        format.json { render json: @private_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_notes/1
  # PATCH/PUT /private_notes/1.json
  def update
    respond_to do |format|
      if @private_note.update(private_note_params)
        format.html { redirect_to @private_note, notice: 'Private note was successfully updated.' }
        format.json { render :show, status: :ok, location: @private_note }
      else
        format.html { render :edit }
        format.json { render json: @private_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_notes/1
  # DELETE /private_notes/1.json
  def destroy
    authorize @private_note
    @private_note.destroy
    respond_to do |format|
      format.html { redirect_to link_path(@private_note.link), notice: 'Note removed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_link
      @link = Link.find(params[:private_note][:link_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_private_note
      @private_note = PrivateNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def private_note_params
      params.require(:private_note).permit(:user_id, :link_id, :body, :title)
    end
end

app/views/private_notes/_form.html.erb
<%= form_with(model: private_note, local: true) do |form| %>
  <% if private_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private_note.errors.count, "error") %> stopped you from saving your note:</h2>

      <ul>
      <% private_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="form-group form-row">
        <div class="col-2">
          <%= form.label :title, class: 'col-form-label' %>
        </div>
        <div class="col-10">
          <%= form.text_field :title, id: :private_note_title, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group form-row">
        <div class="col-2">
          <%= form.label :Note, class: 'col-form-label' %>
        </div>
        <div class="col-10">
          <%= form.text_area :body, id: :private_note_body, class: 'form-control' %>
        </div>
      </div>

      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :link_id %>

      <div class="form-group form-row">
        <div class="col-2">
        </div>
        <div class="col-10">
          <%= form.submit :Submit, class: 'btn btn-primary btn-block float-right' %>
        </div>
      </div>
<% end %>

app/views/private_notes/_link.html.erb
<h4><%= link_to link.title, link_path(link) %></h4>

<%= link_url_helper(link) %>

<% if link.has_instructors? %>
  <ul class="list-inline mt-2">
    <% link.instructors.each do |i| %>
      <li class="list-inline-item">
        <%= link_to i.display_name, i, class: 'btn btn-light btn-sm' %>
      </li>
    <% end %>
  </ul>
<% end %>

<p class="mt-1">
  <% link.tags.each do |tag| %>
    <%= link_to "#{tag.category}::#{tag.name}", tag, class: 'tag' %>
  <% end %>
</p>

<% if link.description_exists? %>
  <hr />
  
  <p class="mt-1">
    <%= link.show_description %>
  </p>
<% end %>

app/views/private_notes/_note.html.erb
            <div class="notebook-paper mb-2">
              <div class="notebook-content">
                <div class="notebook-header">
                  <h3 class="notebook-title"><%= private_note.title %></h3>
                </div>
                <p><%= private_note.body %></p>
              </div>
            </div>

app/views/private_notes/_notebook_list.html.erb
<% if private_notes.size > 0 %>

  <% private_notes.each do |private_note| %>

    <div class="notebook-paper mb-2">
      <div class="notebook-content">
        <div class="notebook-header">
          <h3 class="notebook-title"><%= link_to private_note.title, private_note_path(private_note) %></h3>
          <h6 class="notebook-title"><%= link_to private_note.link.title, link_path(private_note.link) %></h6>
        </div>
        <p><%= truncate(private_note.body, length: 250) %></p>
      </div>
    </div>
 
  <% end %>

<% else %>

  <h5>No entries match <span class="text-primary"><%= params[:private_note_search] %></span></h5>

<% end %>

app/views/private_notes/edit.html.erb
<h1>Editing Private Note</h1>

<%= render 'form', private_note: @private_note %>

<%= link_to 'Show', @private_note %> |
<%= link_to 'Back', private_notes_path %>

app/views/private_notes/index.html.erb
<div class="col">

  <h1 class="mt-4">Notebook</h1>
<table "table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Link</th>
      <th>Title</th>
      <th>Note</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @private_notes.each do |private_note| %>
      <tr>
        <td><%= link_to private_note.user.name, private_note.user.name %></td>
        <td><%= link_to private_note.link.title, private_note.link %></td>
        <td><%= private_note.title %></td>
        <td><%= private_note.body %></td>
        <td><%= link_to 'Show', private_note, class: 'btn btn-light' %></td>
        <td><%= link_to 'Edit', edit_private_note_path(private_note), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Delete', private_note, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center">
        <%== pagy_nav_bootstrap(@pagy) %>
      </div>
    </div>
  </div>

</div>

app/views/private_notes/link_notebook.html.erb
  <div class="card my-4">
    <h5 class="card-header">
      My Notebook
      (<%= @private_notes_link_count %>)
      <button type="button" id="notebook_toggle" class="float-right btn btn-primary">+</button>
    </h5>
    <div id="notebook_body">
      <div class="card-body">
        <h5 class="card-title">New Note</h5>
        <%= render template: 'private_notes/new', locals: { private_note: private_note, link: link } %>
      </div>

      <% if @private_notes.present? %>
        <ul class="list-group list-group-flush">
          <% @private_notes.each do |note| %>
            <li class="list-group-item">
              <div class="card my-2">
                <h6 class="card-header"><%= link_to note.title, private_note_path(note) %></h6>
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <%= note.body %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-6">
                      <%= link_to 'View', note, class: 'btn btn-dark' %>
                      <%= link_to 'Edit', edit_private_note_path(note), class: 'btn btn-primary' %>
                    </div>
                    <div class="col-6 text-right">
                    <%= link_to note.created_at.strftime("%Y-%b-%d"), private_note_path(note) %>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

app/views/private_notes/new.html.erb
<%= render partial: 'private_notes/form', locals: { private_note: private_note, link: link } %>

app/views/private_notes/notebook.html.erb
<div class="col">
  <h1 class="mt-4">My Notebook</h1>

      <%= form_with url: search_private_notes_path, method: :get do |f|%>
        <div class="form-group row">
          <label class="col-form-label col-2 text-right"><h6>Search My Notebook</h6></label>
          <div class="col-3">
            <%= f.text_field :private_note_search, class: 'form-control' %>
            <div style="display:none;"><%= f.submit id: 'submit-search' %></div>
          </div>
          <div class="col-7">
          </div>
        </div>
      <% end %>

  <div id="private_note-display"><%= render partial: 'private_notes/notebook_list', locals: { private_notes: @private_notes } %></div>

  <div class="row">
    <div class="col">
      <div id="pagy-div" class="d-flex justify-content-center">
        <%== pagy_nav_bootstrap(@pagy) %>
      </div>
    </div>
  </div>

</div>

app/views/private_notes/search.js.erb
$(function(){
    $('#private_note-display').html(`<%= render partial: 'private_notes/notebook_list', locals: { private_notes: @private_notes_search } %>`);
    $('#pagy-div').html('<%== pagy_nav_bootstrap(@pagy) %>');
});

app/views/private_notes/show.html.erb
<div class="col">
  <h1 class="mt-4">
    <%= link_to 'My Notebook', notebook_path %>
    &gt;
    <%= @private_note.title %>
  </h1>
  <div class="row mt-4">
    <div class="col-7">
      <div class="container">
        <div class="row mt-5">
          <div class="col-12">
            <%= render partial: 'private_notes/note', locals: { private_note: @private_note } %>
          </div>
          <div class="col-5">
          </div>
          <div class="col-3">
            <div class="center">
              <%= link_to 'Edit', edit_private_note_path(@private_note), class: 'btn btn-primary' %>
              <%= link_to 'Delete', @private_note, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </div>
          </div>
          <div class="col-4">
          </div>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div class="container">
        <%= render partial: 'private_notes/link', locals: { link: @private_note.link } %>
      </div>

    </div>
  </div>
</div>